/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UrlParserImport } from './routes/url-parser'
import { Route as JsonFormatterImport } from './routes/json-formatter'
import { Route as JsonDiffImport } from './routes/json-diff'
import { Route as AsdfImport } from './routes/asdf'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const UrlParserRoute = UrlParserImport.update({
  id: '/url-parser',
  path: '/url-parser',
  getParentRoute: () => rootRoute,
} as any)

const JsonFormatterRoute = JsonFormatterImport.update({
  id: '/json-formatter',
  path: '/json-formatter',
  getParentRoute: () => rootRoute,
} as any)

const JsonDiffRoute = JsonDiffImport.update({
  id: '/json-diff',
  path: '/json-diff',
  getParentRoute: () => rootRoute,
} as any)

const AsdfRoute = AsdfImport.update({
  id: '/asdf',
  path: '/asdf',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/asdf': {
      id: '/asdf'
      path: '/asdf'
      fullPath: '/asdf'
      preLoaderRoute: typeof AsdfImport
      parentRoute: typeof rootRoute
    }
    '/json-diff': {
      id: '/json-diff'
      path: '/json-diff'
      fullPath: '/json-diff'
      preLoaderRoute: typeof JsonDiffImport
      parentRoute: typeof rootRoute
    }
    '/json-formatter': {
      id: '/json-formatter'
      path: '/json-formatter'
      fullPath: '/json-formatter'
      preLoaderRoute: typeof JsonFormatterImport
      parentRoute: typeof rootRoute
    }
    '/url-parser': {
      id: '/url-parser'
      path: '/url-parser'
      fullPath: '/url-parser'
      preLoaderRoute: typeof UrlParserImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/asdf': typeof AsdfRoute
  '/json-diff': typeof JsonDiffRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/url-parser': typeof UrlParserRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/asdf': typeof AsdfRoute
  '/json-diff': typeof JsonDiffRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/url-parser': typeof UrlParserRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/asdf': typeof AsdfRoute
  '/json-diff': typeof JsonDiffRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/url-parser': typeof UrlParserRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/asdf'
    | '/json-diff'
    | '/json-formatter'
    | '/url-parser'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/asdf'
    | '/json-diff'
    | '/json-formatter'
    | '/url-parser'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/asdf'
    | '/json-diff'
    | '/json-formatter'
    | '/url-parser'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AsdfRoute: typeof AsdfRoute
  JsonDiffRoute: typeof JsonDiffRoute
  JsonFormatterRoute: typeof JsonFormatterRoute
  UrlParserRoute: typeof UrlParserRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AsdfRoute: AsdfRoute,
  JsonDiffRoute: JsonDiffRoute,
  JsonFormatterRoute: JsonFormatterRoute,
  UrlParserRoute: UrlParserRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/asdf",
        "/json-diff",
        "/json-formatter",
        "/url-parser"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/asdf": {
      "filePath": "asdf.tsx"
    },
    "/json-diff": {
      "filePath": "json-diff.tsx"
    },
    "/json-formatter": {
      "filePath": "json-formatter.tsx"
    },
    "/url-parser": {
      "filePath": "url-parser.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
